const ADD_TABLE = 'ADD_TABLE';
const ADD_TO_EMPTY_SHOPPING_LIST = 'ADD_TO_EMPTY_SHOPPING_LIST';
const ADD_TO_EXISTING_SHOPPING_LIST = 'ADD_TO_EXISTING_SHOPPING_LIST';
const NO_DATA = 0, LOADING = 1, LOADED = 2;
const SELECT_TAB = 'SELECT_TAB';
const REMOVE_TABLE = 'REMOVE_TABLE';
const UNDO_TABLE = 'UNDO_TABLE';

export {
  ADD_TABLE,
  NO_DATA,
  LOADING,
  LOADED,
  ADD_TO_EMPTY_SHOPPING_LIST,
  ADD_TO_EXISTING_SHOPPING_LIST,
  SELECT_TAB, REMOVE_TABLE, UNDO_TABLE}
