const ADD_TABLE = 'ADD_TABLE';
const ADD_TO_EMPTY_SHOPPING_LIST = 'ADD_TO_EMPTY_SHOPPING_LIST';
const ADD_TO_EXISTING_SHOPPING_LIST = 'ADD_TO_EXISTING_SHOPPING_LIST';
const REMOVE_ONE_TABLE = 'REMOVE_ONE_TABLE';
const NO_DATA = 0, LOADING = 1, LOADED = 2;

export {ADD_TABLE, REMOVE_ONE_TABLE, NO_DATA, LOADING, LOADED, ADD_TO_EMPTY_SHOPPING_LIST, ADD_TO_EXISTING_SHOPPING_LIST}
